// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 05.07.2025, 14:53:38
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/user/Desktop/aurus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/aurus/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/aurus/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/aurus/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/aurus/plugins/**/*.{js,ts,mjs}","C:/Users/user/Desktop/aurus/composables/**/*.{js,ts,mjs}","C:/Users/user/Desktop/aurus/utils/**/*.{js,ts,mjs}","C:/Users/user/Desktop/aurus/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/aurus/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/aurus/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/user/Desktop/aurus/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;