"""Add status to Chat

Revision ID: 8f61286e521f
Revises: adca797ec134
Create Date: 2025-06-26 20:26:24.502830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f61286e521f'
down_revision: Union[str, None] = 'adca797ec134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_logs', 'api_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('chat_logs', 'request_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('chat_logs', 'response_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_chat_logs_api_key'), 'chat_logs', ['api_key'], unique=False)
    op.create_index(op.f('ix_chat_logs_chat_id'), 'chat_logs', ['chat_id'], unique=False)
    op.create_index(op.f('ix_chat_logs_user_id'), 'chat_logs', ['user_id'], unique=False)
    op.add_column('chats', sa.Column('status', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_column('chats', 'status')
    op.drop_index(op.f('ix_chat_logs_user_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_chat_id'), table_name='chat_logs')
    op.drop_index(op.f('ix_chat_logs_api_key'), table_name='chat_logs')
    op.alter_column('chat_logs', 'response_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_logs', 'request_text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('chat_logs', 'api_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
