"""Datebase creation

Revision ID: adca797ec134
Revises: 
Create Date: 2025-06-26 10:34:31.385013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'adca797ec134'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_id'), 'chats', ['id'], unique=False)
    op.drop_table('user')
    op.drop_index('ix_todos_id', table_name='todos')
    op.drop_table('todos')
    op.drop_index('ix_tasks_id', table_name='tasks')
    op.drop_index('ix_tasks_title', table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('reports')
    op.add_column('chat_logs', sa.Column('chat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chat_logs_id'), 'chat_logs', ['id'], unique=False)
    op.create_foreign_key(None, 'chat_logs', 'chats', ['chat_id'], ['id'])
    op.drop_column('chat_logs', 'api_key')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'api_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_constraint('users_username_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_unique_constraint(None, 'users', ['api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_unique_constraint('users_username_key', 'users', ['username'])
    op.alter_column('users', 'api_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('chat_logs', sa.Column('api_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chat_logs', type_='foreignkey')
    op.drop_index(op.f('ix_chat_logs_id'), table_name='chat_logs')
    op.drop_column('chat_logs', 'chat_id')
    op.create_table('reports',
    sa.Column('report_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('report_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('project', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Finance_source', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Customer_bin', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('planner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Planner_bin', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('Место проведения экспертизы', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('БИН экспертной организации', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('kato', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('Object_place', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timelimit', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Object_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Input_report', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Contract_number', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Contract_amount', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Amount_plan', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey')
    )
    op.create_index('ix_tasks_title', 'tasks', ['title'], unique=False)
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='todos_pkey')
    )
    op.create_index('ix_todos_id', 'todos', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK_cace4a159ff9f2512dd42373760')
    )
    op.drop_index(op.f('ix_chats_id'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
